#!/bin/sh

# reload nginx to prevent file lock and immediately clear cache
/usr/local/openresty/bin/openresty -s reload

# delete anything older than 12 hours
find /var/cache/nginx/site/* -daystart -maxdepth 1 -mmin +720 -type f -exec rm -f {} \;
