#!/bin/sh

# reload nginx to prevent file lock and immediately clear cache
nginx -s reload

# delete any files older than 24 hours
find /tmp/* -daystart -maxdepth 1 -mmin +1440 -type f -exec rm -f {} \;
